const mongoose = require("mongoose");

const BotDataSchema = new mongoose.Schema({
  guildId: { type: String, required: true, unique: true },
  channelId: { type: String, require: true },
  gameScoreChannel: { type: String, require: true, unique: true },
  leaderboardChannel: { type: String, require: true, unique: true },
  seasonWinnersChannel: { type: String, require: true, unique: true },

  voted: { type: Array, default: [] },
  votedCopy: { type: Array, default: [] },
  lastMsgCopy: { type: Array, default: [] },
  lastMsg: { type: Array, default: [] },
  lastChMsg: { type: Array, default: [] },
  lastChMsgCopy: { type: Array, default: [] },
  lastRankMsg: { type: Array, default: [] },
  lastRankMsgCopy: { type: Array, default: [] },
  draftPool: { type: Array, default: [] },
  alerted8People: { type: Boolean, default: false },
  alerted8PeopleCopy: { type: Boolean, default: false },
  inDraft: { type: Array, default: [] },
  randomizedAlready: { type: Number, default: 0 },
  team1: { type: Array, default: [] },
  team2: { type: Array, default: [] },
  team1ScoreCopy: { type: Array, default: [] },
  team2ScoreCopy: { type: Array, default: [] },
  dqScore: { type: Array, default: [] },
  regularScore: { type: Array, default: [] },
  nextList: { type: Array, default: [] },
  nextListCopy: { type: Array, default: [] },
  nextPlayerAndTime: { type: Array, default: [] },
  nextPlayerAndTimeCopy: { type: Array, default: [] },
  nextPingedPlayers: { type: Array, default: [] },
  nextPingedPlayersCopy: { type: Array, default: [] },
  team1re: { type: Array, default: [] },
  team2re: { type: Array, default: [] },
  captainsOldList: { type: Array, default: [] },
  team1OldList: { type: Array, default: [] },
  team2OldList: { type: Array, default: [] },
  captains: { type: Array, default: [] },
  namesWithSpaces: { type: Array, default: [] },
  namesWithSpacesCopy: { type: Array, default: [] },
  randomizedDraftList: { type: Array, default: [] },
  randomizedDraftListCopy: { type: Array, default: [] },
  msgIncludesCrown: { type: Boolean, default: false },

  newDraftPingedPlayers: { type: Array, default: [] },
  winnerNames: { type: Array, default: [] },
  loserNames: { type: Array, default: [] },
  leaverNames: { type: Array, default: [] },
  resetCount: { type: Number, default: 0 },
  randomizedCount: { type: Number, default: 0 },
  resetRandomized: { type: Boolean, default: false },
  draftCopy: { type: Array, default: [] },
  draft2Copy: { type: Array, default: [] },
  inDraftDraftCopy: { type: Array, default: [] },
  team1DraftCopy: { type: Array, default: [] },
  team2DraftCopy: { type: Array, default: [] },
  captainsDraftCopy: { type: Array, default: [] },
  startedPicks: { type: Boolean, default: false },
  startedPicksCopy: { type: Boolean, default: false },
  playerAndTime: { type: Array, default: [] },
  playerAndTimeCopy: { type: Array, default: [] },

  team1Win: { type: Number, default: 0 },
  team2Win: { type: Number, default: 0 },
  team2Loss: { type: Number, default: 0 },
  dqWin: { type: Number, default: 0 },
  dqLoss: { type: Number, default: 0 },
  regularWin: { type: Number, default: 0 },
  regularLoss: { type: Number, default: 0 },
  banList: { type: Array, default: [] },
  playerAndTime: { type: Array, default: [] },
  playerAndTimeCopy: { type: Array, default: [] },
  peopleSymbol: { type: String, default: "::" },
  dashSymbol: { type: String, default: "" },
  commandSymbol: { type: String, default: "$" },
  oldListArr1: { type: Array, default: [] },
  oldListArr2: { type: Array, default: [] },
  listArr: {
    type: Array,
    default: [
      "::",
      `**0**`,
      "\n",
      `\n **Draft List**:`,
      "\n\n",
      "\n",
      "**Team 1**:",
      "\n",
      "\n",
      "**Team 2**:",
    ],
  },
  randomizedArr: {
    type: Array,
    default: [
      "::",
      `0`,
      "\n",
      "\n",
      "**Team 1**:",
      " ",
      ``,
      "\n",
      "\n",
      "**Team 2**:",
      "\n",
      "\n",
    ],
  },
});

const botData = mongoose.model("bot data", BotDataSchema);
botData.createIndexes({ guildId: 1 });

module.exports = botData;
